name: saol
favicon: null
layout_spectrum: 0.5127
typography_spectrum: 0.99002
title: Staffan Lundgren
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#adb7ae'
    - '#657072'
    - '#3b494c'
    - '#ddd8ba'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
