name: saol
favicon: null
layout_spectrum: 0.969368212390691
typography_spectrum: 0.47374
title: Staffan Lundgren
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edece7'
    - '#282142'
    - '#d9c6bf'
    - '#bea09e'
    - '#685f74'
  brandStrength: 0.5
  lightness: 0.6713694136124104
  saturation: 0.8874841541983187
  rhythmicContrast: 0.14009207230992615
purpose: []
